main: dev.zomo.acmd.acmd
version: ${project.version}
name: admin-commands
author: Ashley Zomo
api-version: 1.16
depend: [Minecraft-Premium]

commands:
  fcmd:
    description: force person to run command
    permission: fcmd.fcmd
    usage: /<command> <target> <execCommand>
  base:
    description: find someone's spawnpoint/base
    permission: fcmd.base
    usage: /<command> <target>
  loc:
    description: find someone's location/last location
    permission: fcmd.loc
    usage: /<command> <target>
  vanish:
    description: toggle vanish mode
    permission: fcmd.vanish
    usage: /<command>
  fly:
    description: toggle fly mode
    permission: fcmd.fly
    usage: /<command>
  god:
    description: toggle god mode
    permission: fcmd.god
    usage: /<command>
  top:
    description: teleport to top
    permission: fcmd.top
    usage: /<command>
  flyspeed:
    description: set fly speed
    permission: fcmd.flyspeed
    usage: /<command> <speed>
  sethealth:
    description: set health level
    permission: fcmd.health
    usage: /<command> <target> <health>
  sethunger:
    description: set hunger level
    permission: fcmd.hunger
    usage: /<command> <target> <hunger>
  admin:
    description: toggle admin mode
    permission: fcmd.admin
    usage: /<command>
  ban:
    description: ban someone
    permission: fcmd.ban
    usage: /<command> <target> [<reason>]
  tempban:
    description: tempban someone
    permission: fcmd.ban
    usage: /<command> <target> <time> [<reason>]
  untempban:
    description: untempban someone
    permission: fcmd.ban
    usage: /<command> <target>
  unban:
    description: unban someone
    permission: fcmd.ban
    usage: /<command> <target>
  baninfo:
    description: get information about someone's ban
    permission: fcmd.ban
    usage: /<command> <target>
  

permissions:
  acmd.*:
    description: Gives access to all acmd commands
    children:
      acmd.fcmd: true
      fcmd.base: true
      fcmd.loc: true
      fcmd.vanish: true
      fcmd.fly: true
      fcmd.god: true
      fcmd.top: true
      fcmd.flyspeed: true
      fcmd.health: true
      fcmd.hunger: true
      fcmd.admin: true
      fcmd.ban: true
  acmd.fcmd:
    description: Allows access to /fcmd command
    default: false
  fcmd.base:
    description: Allows access to /base command
    default: false
  fcmd.loc:
    description: Allows access to /loc command
    default: false
  fcmd.vanish:
    description: Allows access to /vanish command
    default: false
  fcmd.fly:
    description: Allows access to /fly command
    default: false
  fcmd.god:
    description: Allows access to /god command
    default: false
  fcmd.top:
    description: Allows access to /top command
    default: false
  fcmd.flyspeed:
    description: Allows access to /flyspeed command
    default: false
  fcmd.health:
    description: Allows access to /sethealth command
    default: false
  fcmd.hunger:
    description: Allows access to /sethunger command
    default: false
  fcmd.admin:
    description: Allows access to /admin command
    default: false
  fcmd.ban:
    description: Allows access to /ban and /tempban commands
    default: false